name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up SSH Key
      run: |
        echo "${{ secrets.EC2_KEY }}" > ~/DjangoCDKey.pem
        chmod 400 ~/DjangoCDKey.pem

    - name: Deploy Code
      run: |
        scp -o StrictHostKeyChecking=no -i ~/DjangoCDKey.pem -r ./* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ec2-user/Django_Project/
        ssh -o StrictHostKeyChecking=no -i ~/DjangoCDKey.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
          cd /home/ec2-user/Django_Project &&
          docker-compose up --build -d
        "
